<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-android</TargetFramework>
		<SupportedOSPlatformVersion>21.0</SupportedOSPlatformVersion>
		<OutputType>Exe</OutputType>
		<ApplicationId>com.vallequebrado.rpg</ApplicationId>
		<ApplicationVersion>1</ApplicationVersion>
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AndroidPackageFormat>apk</AndroidPackageFormat>
		<AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MonoGame.Framework.Android" Version="3.8.1.303" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove=".dotnet/**" />
		<Compile Remove="bin/**" />
		<Compile Remove="obj/**" />
	</ItemGroup>

</Project>
