<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<OutputType>Exe</OutputType>
		<ApplicationId>com.vallequebrado.rpg</ApplicationId>
		<ApplicationVersion>1</ApplicationVersion>
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RuntimeIdentifier>linux-arm64</RuntimeIdentifier>
		<PublishReadyToRun>true</PublishReadyToRun>
		<PublishTrimmed>false</PublishTrimmed>
		<PublishSingleFile>false</PublishSingleFile>
		<SelfContained>true</SelfContained>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.1.303" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove=".dotnet/**" />
		<Compile Remove="bin/**" />
		<Compile Remove="obj/**" />
	</ItemGroup>

</Project>
